### ISSUE TITLE
additional coffee compile parameter

### ISSUE THREAD

**Issue by neotohin** [DamonOehlman/grunt-rigger#7]
I want to ignore coffee's auto closure for my scripts. I can do this by passing : -b bare parameter for coffee compilation. How can i do this in rigger.

**Comment by DamonOehlman** [comment]
It looks like while rigger would be quite happy to pass through the required programmatic option directly to the coffeescript compile function, that the grunt-rigger doesn't pass through many options to rigger.  This is something that could definitely be changed though.

**Comment by airmrcr** [comment]
I was going to use this plugin for a new project of mine, but I noticed that my CoffeeScript output was not "bare" and that it can't be configured to be. I would really appreciate the ability to cascade options to the compiler. The key reason I'm using rigger is because I'm creating a factory-wrapper for my code, so having that wrapped in an IIFE seems a bit pointless.

**Comment by DamonOehlman** [comment]
I used the train ride this morning to get this sorted - if you install `grunt-rigger@0.6` then you will be able to specify "bare: true" in the task options:

https://github.com/DamonOehlman/grunt-rigger/blob/master/Gruntfile.js#L89-96

**Comment by airmrcr** [comment]
Thanks for adding this! I can confirm that it worked perfectly for me.

**Comment by DamonOehlman** [comment]
Fantastic - that's great news :)
